# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steamnetworkingsockets_messages_certs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='steamnetworkingsockets_messages_certs.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n+steamnetworkingsockets_messages_certs.proto\"\x8f\x01\n\x1b\x43MsgSteamNetworkingIdentity\x12\x10\n\x08steam_id\x18\x10 \x01(\x06\x12\x18\n\x10xbox_pairwise_id\x18\x11 \x01(\t\x12\x15\n\rgeneric_bytes\x18\x02 \x01(\x0c\x12\x16\n\x0egeneric_string\x18\x03 \x01(\t\x12\x15\n\ripv6_and_port\x18\x04 \x01(\x0c\"\xc1\x02\n\x1c\x43MsgSteamDatagramCertificate\x12\x41\n\x08key_type\x18\x01 \x01(\x0e\x32&.CMsgSteamDatagramCertificate.EKeyType:\x07INVALID\x12\x10\n\x08key_data\x18\x02 \x01(\x0c\x12\x17\n\x0flegacy_steam_id\x18\x04 \x01(\x06\x12.\n\x08identity\x18\x0b \x01(\x0b\x32\x1c.CMsgSteamNetworkingIdentity\x12!\n\x19gameserver_datacenter_ids\x18\x05 \x03(\x07\x12\x14\n\x0ctime_created\x18\x08 \x01(\x07\x12\x13\n\x0btime_expiry\x18\t \x01(\x07\x12\x0f\n\x07\x61pp_ids\x18\n \x03(\r\"$\n\x08\x45KeyType\x12\x0b\n\x07INVALID\x10\x00\x12\x0b\n\x07\x45\x44\x32\x35\x35\x31\x39\x10\x01\"[\n\"CMsgSteamDatagramCertificateSigned\x12\x0c\n\x04\x63\x65rt\x18\x04 \x01(\x0c\x12\x11\n\tca_key_id\x18\x05 \x01(\x06\x12\x14\n\x0c\x63\x61_signature\x18\x06 \x01(\x0c\x42\x05H\x01\x80\x01\x00')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CMSGSTEAMDATAGRAMCERTIFICATE_EKEYTYPE = _descriptor.EnumDescriptor(
  name='EKeyType',
  full_name='CMsgSteamDatagramCertificate.EKeyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ED25519', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=479,
  serialized_end=515,
)
_sym_db.RegisterEnumDescriptor(_CMSGSTEAMDATAGRAMCERTIFICATE_EKEYTYPE)


_CMSGSTEAMNETWORKINGIDENTITY = _descriptor.Descriptor(
  name='CMsgSteamNetworkingIdentity',
  full_name='CMsgSteamNetworkingIdentity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steam_id', full_name='CMsgSteamNetworkingIdentity.steam_id', index=0,
      number=16, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xbox_pairwise_id', full_name='CMsgSteamNetworkingIdentity.xbox_pairwise_id', index=1,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='generic_bytes', full_name='CMsgSteamNetworkingIdentity.generic_bytes', index=2,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='generic_string', full_name='CMsgSteamNetworkingIdentity.generic_string', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ipv6_and_port', full_name='CMsgSteamNetworkingIdentity.ipv6_and_port', index=4,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=191,
)


_CMSGSTEAMDATAGRAMCERTIFICATE = _descriptor.Descriptor(
  name='CMsgSteamDatagramCertificate',
  full_name='CMsgSteamDatagramCertificate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_type', full_name='CMsgSteamDatagramCertificate.key_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key_data', full_name='CMsgSteamDatagramCertificate.key_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='legacy_steam_id', full_name='CMsgSteamDatagramCertificate.legacy_steam_id', index=2,
      number=4, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='CMsgSteamDatagramCertificate.identity', index=3,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gameserver_datacenter_ids', full_name='CMsgSteamDatagramCertificate.gameserver_datacenter_ids', index=4,
      number=5, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_created', full_name='CMsgSteamDatagramCertificate.time_created', index=5,
      number=8, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_expiry', full_name='CMsgSteamDatagramCertificate.time_expiry', index=6,
      number=9, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_ids', full_name='CMsgSteamDatagramCertificate.app_ids', index=7,
      number=10, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CMSGSTEAMDATAGRAMCERTIFICATE_EKEYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=515,
)


_CMSGSTEAMDATAGRAMCERTIFICATESIGNED = _descriptor.Descriptor(
  name='CMsgSteamDatagramCertificateSigned',
  full_name='CMsgSteamDatagramCertificateSigned',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cert', full_name='CMsgSteamDatagramCertificateSigned.cert', index=0,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ca_key_id', full_name='CMsgSteamDatagramCertificateSigned.ca_key_id', index=1,
      number=5, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ca_signature', full_name='CMsgSteamDatagramCertificateSigned.ca_signature', index=2,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=608,
)

_CMSGSTEAMDATAGRAMCERTIFICATE.fields_by_name['key_type'].enum_type = _CMSGSTEAMDATAGRAMCERTIFICATE_EKEYTYPE
_CMSGSTEAMDATAGRAMCERTIFICATE.fields_by_name['identity'].message_type = _CMSGSTEAMNETWORKINGIDENTITY
_CMSGSTEAMDATAGRAMCERTIFICATE_EKEYTYPE.containing_type = _CMSGSTEAMDATAGRAMCERTIFICATE
DESCRIPTOR.message_types_by_name['CMsgSteamNetworkingIdentity'] = _CMSGSTEAMNETWORKINGIDENTITY
DESCRIPTOR.message_types_by_name['CMsgSteamDatagramCertificate'] = _CMSGSTEAMDATAGRAMCERTIFICATE
DESCRIPTOR.message_types_by_name['CMsgSteamDatagramCertificateSigned'] = _CMSGSTEAMDATAGRAMCERTIFICATESIGNED

CMsgSteamNetworkingIdentity = _reflection.GeneratedProtocolMessageType('CMsgSteamNetworkingIdentity', (_message.Message,), dict(
  DESCRIPTOR = _CMSGSTEAMNETWORKINGIDENTITY,
  __module__ = 'steamnetworkingsockets_messages_certs_pb2'
  # @@protoc_insertion_point(class_scope:CMsgSteamNetworkingIdentity)
  ))
_sym_db.RegisterMessage(CMsgSteamNetworkingIdentity)

CMsgSteamDatagramCertificate = _reflection.GeneratedProtocolMessageType('CMsgSteamDatagramCertificate', (_message.Message,), dict(
  DESCRIPTOR = _CMSGSTEAMDATAGRAMCERTIFICATE,
  __module__ = 'steamnetworkingsockets_messages_certs_pb2'
  # @@protoc_insertion_point(class_scope:CMsgSteamDatagramCertificate)
  ))
_sym_db.RegisterMessage(CMsgSteamDatagramCertificate)

CMsgSteamDatagramCertificateSigned = _reflection.GeneratedProtocolMessageType('CMsgSteamDatagramCertificateSigned', (_message.Message,), dict(
  DESCRIPTOR = _CMSGSTEAMDATAGRAMCERTIFICATESIGNED,
  __module__ = 'steamnetworkingsockets_messages_certs_pb2'
  # @@protoc_insertion_point(class_scope:CMsgSteamDatagramCertificateSigned)
  ))
_sym_db.RegisterMessage(CMsgSteamDatagramCertificateSigned)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001\200\001\000'))
# @@protoc_insertion_point(module_scope)
